name: language_hack
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_swipable: ^1.2.1

  form_field_validator: ^1.1.0

  firebase_auth: ^1.1.0

  firebase_storage: ^8.0.3

  cloud_firestore: ^1.0.5

  firebase_core: ^1.6.0

  fluttertoast: ^8.0.8

  flutter_tts: ^3.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  cherry_toast: ^1.0.2

  hexcolor: ^2.0.5

  introduction_screen: ^2.1.0

  motion_toast: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg.png
    - assets/logo.png
    - assets/animal.png
    - assets/card1.png

    - assets/rejected.png
    - assets/banana.png
    - assets/swipeLeft.png
    - assets/swipeRight.png

    - assets/on-boarding1.png
    - assets/on-boarding2.png
    - assets/on-boarding3.png
    - assets/on-boarding4.png

    - assets/notebook.png
    - assets/reading-book.png

    - assets/color.png
    - assets/fruit.png
    - assets/family.png
    - assets/countries.png
    - assets/vegetables.png
    - assets/places.png
    - assets/days.png
    - assets/months.png
    - assets/verb.png
    - assets/adjectives.png

    - assets/Color/1.png
    - assets/Color/2.png
    - assets/Color/3.png
    - assets/Color/4.png
    - assets/Color/5.png
    - assets/Color/6.png
    - assets/Color/7.png
    - assets/Color/8.png
    - assets/Color/9.png
    - assets/Color/10.png

    - assets/Countries/1.png
    - assets/Countries/2.png
    - assets/Countries/3.png
    - assets/Countries/4.png
    - assets/Countries/5.png
    - assets/Countries/6.png
    - assets/Countries/7.png
    - assets/Countries/8.png
    - assets/Countries/9.png
    - assets/Countries/10.png

    - assets/Days/1.png
    - assets/Days/2.png
    - assets/Days/3.png
    - assets/Days/4.png
    - assets/Days/5.png
    - assets/Days/6.png
    - assets/Days/7.png

    - assets/Family/1.png
    - assets/Family/2.png
    - assets/Family/3.png
    - assets/Family/4.png
    - assets/Family/5.png
    - assets/Family/6.png
    - assets/Family/7.png
    - assets/Family/8.png
    - assets/Family/9.png
    - assets/Family/10.png

    - assets/Fruit/1.png
    - assets/Fruit/2.png
    - assets/Fruit/3.png
    - assets/Fruit/4.png
    - assets/Fruit/5.png
    - assets/Fruit/6.png
    - assets/Fruit/7.png
    - assets/Fruit/8.png
    - assets/Fruit/9.png
    - assets/Fruit/10.png

    - assets/Months/1.png
    - assets/Months/2.png
    - assets/Months/3.png
    - assets/Months/4.png
    - assets/Months/5.png
    - assets/Months/6.png
    - assets/Months/7.png
    - assets/Months/8.png
    - assets/Months/9.png
    - assets/Months/10.png
    - assets/Months/11.png
    - assets/Months/12.png

    - assets/Places/1.png
    - assets/Places/2.png
    - assets/Places/3.png
    - assets/Places/4.png
    - assets/Places/5.png
    - assets/Places/6.png
    - assets/Places/7.png
    - assets/Places/8.png
    - assets/Places/9.png
    - assets/Places/10.png

    - assets/Vegetables/1.png
    - assets/Vegetables/2.png
    - assets/Vegetables/3.png
    - assets/Vegetables/4.png
    - assets/Vegetables/5.png
    - assets/Vegetables/6.png
    - assets/Vegetables/7.png
    - assets/Vegetables/8.png
    - assets/Vegetables/9.png
    - assets/Vegetables/10.png

    - assets/Verbs/1.png
    - assets/Verbs/2.png
    - assets/Verbs/3.png
    - assets/Verbs/4.png
    - assets/Verbs/5.png
    - assets/Verbs/6.png
    - assets/Verbs/7.png
    - assets/Verbs/8.png
    - assets/Verbs/9.png
    - assets/Verbs/10.png

    - assets/Adjectives/1.png
    - assets/Adjectives/2.png
    - assets/Adjectives/3.png
    - assets/Adjectives/4.png
    - assets/Adjectives/5.png
    - assets/Adjectives/6.png
    - assets/Adjectives/7.png
    - assets/Adjectives/8.png
    - assets/Adjectives/9.png
    - assets/Adjectives/10.png

    # this is intermediate vocab

    - assets/Clothes/1.png
    - assets/Clothes/2.png
    - assets/Clothes/3.png
    - assets/Clothes/4.png
    - assets/Clothes/5.png
    - assets/Clothes/6.png
    - assets/Clothes/7.png
    - assets/Clothes/8.png
    - assets/Clothes/9.png
    - assets/Clothes/10.png

    - assets/DeFood/1.png
    - assets/DeFood/2.png
    - assets/DeFood/3.png
    - assets/DeFood/4.png
    - assets/DeFood/5.png
    - assets/DeFood/6.png
    - assets/DeFood/7.png
    - assets/DeFood/8.png
    - assets/DeFood/9.png
    - assets/DeFood/10.png

    - assets/Feelings/1.png
    - assets/Feelings/2.png
    - assets/Feelings/3.png
    - assets/Feelings/4.png
    - assets/Feelings/5.png
    - assets/Feelings/6.png
    - assets/Feelings/7.png
    - assets/Feelings/8.png
    - assets/Feelings/9.png
    - assets/Feelings/10.png

    - assets/Football/1.png
    - assets/Football/2.png
    - assets/Football/3.png
    - assets/Football/4.png
    - assets/Football/5.png
    - assets/Football/6.png
    - assets/Football/7.png
    - assets/Football/8.png
    - assets/Football/9.png
    - assets/Football/10.png

    - assets/Halloween/1.png
    - assets/Halloween/2.png
    - assets/Halloween/3.png
    - assets/Halloween/4.png
    - assets/Halloween/5.png
    - assets/Halloween/6.png
    - assets/Halloween/7.png
    - assets/Halloween/8.png
    - assets/Halloween/9.png
    - assets/Halloween/10.png

    - assets/Musical/1.png
    - assets/Musical/2.png
    - assets/Musical/3.png
    - assets/Musical/4.png
    - assets/Musical/5.png
    - assets/Musical/6.png
    - assets/Musical/7.png
    - assets/Musical/8.png
    - assets/Musical/9.png
    - assets/Musical/10.png

    - assets/Office/1.png
    - assets/Office/2.png
    - assets/Office/3.png
    - assets/Office/4.png
    - assets/Office/5.png
    - assets/Office/6.png
    - assets/Office/7.png

    - assets/Sports/1.png
    - assets/Sports/2.png
    - assets/Sports/3.png
    - assets/Sports/4.png
    - assets/Sports/5.png
    - assets/Sports/6.png
    - assets/Sports/7.png

    - assets/Weather/1.png
    - assets/Weather/2.png
    - assets/Weather/3.png
    - assets/Weather/4.png
    - assets/Weather/5.png
    - assets/Weather/6.png

    - assets/FoodType/1.png
    - assets/FoodType/2.png
    - assets/FoodType/3.png
    - assets/FoodType/4.png
    - assets/FoodType/5.png
    - assets/FoodType/6.png

    - assets/Environment/1.png
    - assets/Environment/2.png
    - assets/Environment/3.png
    - assets/Environment/4.png
    - assets/Environment/5.png

    - assets/IELT/1.png
    - assets/IELT/2.png
    - assets/IELT/3.png
    - assets/IELT/4.png
    - assets/IELT/5.png
    - assets/IELT/6.png

    - assets/PartsCar/1.png
    - assets/PartsCar/2.png
    - assets/PartsCar/3.png
    - assets/PartsCar/4.png
    - assets/PartsCar/5.png
    - assets/PartsCar/6.png

    - assets/TOEFL/1.png
    - assets/TOEFL/2.png
    - assets/TOEFL/3.png
    - assets/TOEFL/4.png
    - assets/TOEFL/5.png
    - assets/TOEFL/6.png

    - assets/Workshop/1.png
    - assets/Workshop/2.png
    - assets/Workshop/3.png
    - assets/Workshop/4.png
    - assets/Workshop/5.png
    - assets/Workshop/6.png

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
